schema:
  format:
    openapi: "3.0.0"
  service_input_type: "CrudServiceInput"
  pipeline_input_type: "PipelineInputs"

  types:
    CrudServiceInput:
      type: object
      description: "Input properties for a Lambda backed CRUD API. When given a resource name, this input will be used to generate Create, Read, Update and Delete API methods and lambdas."
      properties:
        resource_handler:
          type: string
          description: "The handler path to find the CRUD methods for this API"
          minLength: 1
          maxLength: 50
          default: "lambda_function.lambda_handler"
        lambda_memory:
          type: number
          description: "The size of your Lambda functions in MB"
          default: 512
          minimum: 1
          maximum: 3008
        lambda_timeout:
          type: number
          description: "The timeout in seconds of your Lambda function"
          default: 30
          minimum: 1
          maximum: 900
        lambda_runtime:
          type: string
          description: "The runtime for your Lambda service"
          enum: ["nodejs12.x", "python3.8", "ruby2.7", "java11", "go1.x", "dotnetcore3.1"]
          default: "python3.8"
        code_uri:
          type: string
          description: "The s3 link to your application"
          minLength: 1
          maxLength: 200

    PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        unit_test_command:
          type: string
          description: "The command to run to unit test the application code"
          default: "echo 'add your unit test command here'"
          minLength: 1
          maxLength: 200
        lambda_function_uri:
          type: string
          default: s3://cds-protonpoc-s3bucket/python_lambda_function/lambda_function.zip
          minLength: 1
          maxLength: 200